### ISSUE TITLE
Understand how to use run.sh and document potential issues

### ISSUE THREAD

**Issue by wmrifenb** [team-inrs/CarND-Capstone#15]

**Comment by adattudos** [comment]
run.sh is just a script to run the Docker container for the Capstone project as documented here:
https://github.com/bydavy/CarND-Capstone-Docker

The bydavy/capstone docker image is available on docker hub:
https://hub.docker.com/r/bydavy/carnd-capstone/

This is a convenient way to launch the container. Running the script again will attach to it using bash.

However there are issues:
-the base image in the Dockerfile is ubuntu:16.04 so there is no support for nvidia-docker and GPUs:
See https://github.com/bydavy/CarND-Capstone-Docker/commit/ed4386a11ae82a483db920ea1c356f5c29428d82
-in fact it does not even use SSE or AVX instructions...
-it uses an outdated requirements.txt file with Pillow==2.2.1
See https://github.com/bydavy/CarND-Capstone-Docker/blob/master/requirements.txt

So I suggest not to use run.sh at this stage. We might adapt it for nvidia-docker and use it with a GPU enabled docker image later.

Comments welcome.

**Comment by adattudos** [comment]
Try https://github.com/SiliconCar/CarND-Capstone-Docker/blob/master/utils/run_cuda.sh instead.
It uses nvidia-docker with GPU support and has a newer Pillow version installed. We could merge that into the project repo or clone it under team-inrs if it works well.
