### ISSUE TITLE
Find out if and how Carla will provide traffic light locations

### ISSUE THREAD

**Issue by wmrifenb** [team-inrs/CarND-Capstone#16]

**Comment by adattudos** [comment]
https://github.com/udacity/CarND-Capstone/blob/master/ros/src/tl_detector/tl_detector.py#L29-L35

/vehicle/traffic_lights provides you with the location of the traffic light in 3D map space and
        helps you acquire an accurate ground truth data source for the traffic light
        classifier by sending the current color state of all traffic lights in the
        simulator. When testing on the vehicle, the color state will not be available. You'll need to
        rely on the position of the light and the camera image to predict it.
